Usage: uvicorn [OPTIONS] APP
Try 'uvicorn --help' for help.

Error: no such option: --host:0.0.0.0
INFO:     Will watch for changes in these directories: ['/workspace/Bulb_Website/Web/backend']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1859] using StatReload
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Will watch for changes in these directories: ['/workspace/Bulb_Website/Web/backend']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1870] using StatReload
INFO:     Started server process [1875]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:54024 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:54024 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:54266 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:54266 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:54266 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:54266 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:55820 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:55820 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:53066 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:53066 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:53090 - "GET /api/analysis/Detail/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:40200 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:40200 - "GET / HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:59038 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:59038 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:39804 - "GET / HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:50682 - "GET / HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:34230 - "GET / HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:44864 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:44864 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:44866 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:44866 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:44866 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:44866 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:44868 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:44868 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:45116 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:45116 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:45340 - "GET /api HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:45340 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:45854 - "GET /api/topic/list/s HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 238, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "./domain/topic/topic_router.py", line 15, in word2id
    topic = db.query(Topic).filter(Topic.keyword_id == keyword[0].keyword_id).all()
IndexError: list index out of range
INFO:     172.17.0.1:45856 - "GET /api/topic/list/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:45866 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:49782 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:49782 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:53952 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:53962 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:53962 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:53962 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:53962 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:53962 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54040 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54202 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54202 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'main.py'. Reloading...
WARNING:  StatReload detected changes in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1875]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [2694]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:55754 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:55754 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:55754 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:55754 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:55754 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'main.py'. Reloading...
WARNING:  StatReload detected changes in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2694]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [2711]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:55756 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:55766 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:55766 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:36864 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:36862 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:36862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:36862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:36862 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:36862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:36862 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:36866 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:36862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37012 - "GET /api/analysis/Detail/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:37012 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37114 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37114 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:37114 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37860 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:37862 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38100 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38100 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38100 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38102 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38104 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38344 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38598 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38640 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38760 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38760 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38760 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38760 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38760 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38760 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38760 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38760 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38760 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38760 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38760 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38760 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38852 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38852 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38852 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38852 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38852 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38852 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38852 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38852 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38854 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38854 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38854 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38854 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38854 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38854 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38854 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38854 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:38854 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:38854 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:39002 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:39002 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:39002 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:39002 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:44240 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:44250 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:44250 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:44250 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:44252 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:44250 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:44250 - "GET /api/analysis/brief/1 HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:44946 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:44946 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:44946 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:45272 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:45272 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:45272 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:45272 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:45482 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:45482 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:45482 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46482 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46482 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:46482 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46482 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46680 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:46680 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46680 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46714 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46714 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46714 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:46716 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:46716 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:47452 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:47462 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:47462 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:47462 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:47462 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:47462 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:50454 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2711]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [12958]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:53344 - "GET /api/analysis/Detail/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 264, in app
    is_coroutine=is_coroutine,
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Analysis
response
  value is not a valid dict (type=type_error.dict)
INFO:     172.17.0.1:53410 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:53410 - "GET /openapi.json HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Shutting down
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12958]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [13075]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Shutting down
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13075]
ERROR:    Error loading ASGI app. Could not import module "index".
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 3, in <module>
    from domain.analysis import analysis_router
  File "./domain/analysis/analysis_router.py", line 5, in <module>
    from domain.analysis import analysis_schema, analysis_crud
  File "./domain/analysis/analysis_schema.py", line 20, in <module>
    class brief_Analysis(BaseModel):
  File "./domain/analysis/analysis_schema.py", line 23, in brief_Analysis
    topic_name
NameError: name 'topic_name' is not defined
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [13143]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:53650 - "GET /api/analysis/Brief/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 264, in app
    is_coroutine=is_coroutine,
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for brief_Analysis
response -> topic_name
  field required (type=value_error.missing)
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13143]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [13202]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:53842 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13202]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [13250]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13250]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [14411]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'domain/analysis/analysis_crud.py'. Reloading...
WARNING:  StatReload detected changes in 'domain/analysis/analysis_crud.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14411]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [14463]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:54260 - "GET /api/analysis/Detail/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 238, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "./domain/analysis/analysis_router.py", line 14, in question_detail
    analysis = analysis_crud.get_Analysis(db, topic_id=topic_id)
  File "./domain/analysis/analysis_crud.py", line 9, in get_Analysis
    analysis.topic_name = db.query(Keyword).filter(Keyword.keyword_id==1).one().topic_name
NameError: name 'Keyword' is not defined
INFO:     172.17.0.1:54270 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:54270 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:54272 - "GET /api/analysis/Detail/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 238, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "./domain/analysis/analysis_router.py", line 14, in question_detail
    analysis = analysis_crud.get_Analysis(db, topic_id=topic_id)
  File "./domain/analysis/analysis_crud.py", line 9, in get_Analysis
    analysis.topic_name = db.query(Keyword).filter(Keyword.keyword_id==1).one().topic_name
NameError: name 'Keyword' is not defined
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14463]
WARNING:  StatReload detected changes in 'domain/analysis/analysis_schema.py'. Reloading...
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [14612]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:54282 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:54282 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:54282 - "GET /api/analysis/Detail/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 238, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "./domain/analysis/analysis_router.py", line 14, in question_detail
    analysis = analysis_crud.get_Analysis(db, topic_id=topic_id)
  File "./domain/analysis/analysis_crud.py", line 9, in get_Analysis
    analysis.topic_name = db.query(Keyword).filter(Keyword.keyword_id==1).one().topic_name
NameError: name 'Keyword' is not defined
WARNING:  StatReload detected changes in 'domain/analysis/analysis_crud.py'. Reloading...
INFO:     Shutting down
WARNING:  StatReload detected changes in 'domain/analysis/analysis_crud.py'. Reloading...
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14612]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [14845]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:54318 - "GET /api/analysis/Detail/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 238, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "./domain/analysis/analysis_router.py", line 14, in question_detail
    analysis = analysis_crud.get_Analysis(db, topic_id=topic_id)
  File "./domain/analysis/analysis_crud.py", line 11, in get_Analysis
    return analysis_with_name
NameError: name 'analysis_with_name' is not defined
WARNING:  StatReload detected changes in 'domain/analysis/analysis_crud.py'. Reloading...
WARNING:  StatReload detected changes in 'domain/analysis/analysis_crud.py'. Reloading...
INFO:     Shutting down
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14845]
INFO:     Started server process [14893]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:54320 - "GET /api/analysis/Detail/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'domain/analysis/analysis_router.py'. Reloading...
INFO:     Shutting down
WARNING:  StatReload detected changes in 'domain/analysis/analysis_router.py'. Reloading...
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14893]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [14991]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:54340 - "GET /api/analysis/Brief/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 264, in app
    is_coroutine=is_coroutine,
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 2 validation errors for brief_Analysis
response -> topic_name
  field required (type=value_error.missing)
response -> isBig
  field required (type=value_error.missing)
WARNING:  StatReload detected changes in 'domain/analysis/analysis_router.py'. Reloading...
INFO:     Shutting down
WARNING:  StatReload detected changes in 'domain/analysis/analysis_router.py'. Reloading...
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14991]
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Started server process [15221]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:54376 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54402 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54402 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54402 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54402 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54402 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54414 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54414 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54416 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54416 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'domain/analysis/analysis_router.py'. Reloading...
WARNING:  StatReload detected changes in 'domain/analysis/analysis_router.py'. Reloading...
INFO:     Shutting down
ERROR:    Error loading ASGI app. Could not import module "index".
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [15221]
INFO:     Started server process [15812]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     172.17.0.1:54716 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54716 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54716 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54736 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54736 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54736 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54736 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54736 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54736 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54736 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54736 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54738 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54748 - "GET /api/topic/list/%EB%96%B5%EA%B0%9C HTTP/1.1" 200 OK
INFO:     172.17.0.1:54748 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
INFO:     172.17.0.1:54748 - "GET /api/analysis/Brief/1 HTTP/1.1" 200 OK
